# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170318_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
